{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "email": "support@elamp.fr",
      "name": "API support"
    },
    "description": "",
    "license": {
      "name": "eLamp",
      "url": "https://www.elamp.fr/"
    },
    "termsOfService": "https://www.elamp.fr/",
    "title": "eLamp Web API",
    "version": "1.0.0",
    "x-logo": "https://d13ohmdfxbevj9.cloudfront.net/assets/img/LOGO-SLOGAN-COLOR-ALPHA-SMALL.png"
  },
  "servers": [
    {
      "url": "https://api.elamp.fr/v1"
    }
  ],
  "paths": {
    "/groups": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "group.read"
            ]
          }
        ],
        "tags": [
          "IAM"
        ],
        "description": "returns a list of **group** objects.",
        "operationId": "iam.groups.list",
        "summary": "lists groups"
      }
    },
    "/groups/{_key}": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "group.read"
            ]
          }
        ],
        "tags": [
          "IAM"
        ],
        "description": "returns a single **group** object.",
        "operationId": "iam.groups.get",
        "summary": "get group by id"
      }
    },
    "/libraries": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.library.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of available **skills libraries**",
        "operationId": "skills.libraries.list",
        "summary": "lists libraries"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.library"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "creates a new **skills library**",
        "operationId": "skills.libraries.create",
        "summary": "creates libraries"
      }
    },
    "/libraries/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.library"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the deleted **library**.\n",
        "operationId": "skills.libraries.delete",
        "summary": "deletes a library by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.library.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a **skills library** by key.",
        "operationId": "skills.libraries.get",
        "summary": "gets a library by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "skill.library"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the updated **library**.\n",
        "operationId": "skills.libraries.update",
        "summary": "updates a library by key"
      }
    },
    "/libraries/{_key}/subscribe": {
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.library"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the subscribed **skills library**.",
        "operationId": "skills.libraries.subscribe",
        "summary": "subscribe to a library by key"
      }
    },
    "/libraries/{_key}/unsubscribe": {
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.library"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the unsubscribed **skills library**.",
        "operationId": "skills.libraries.unsubscribe",
        "summary": "unsubscribe to a library by key"
      }
    },
    "/pins": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "pin.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **pin** objects for an user",
        "operationId": "pins.list",
        "summary": "list pins of an user"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "pin"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "creates a **pin** object for an user",
        "operationId": "pins.create",
        "summary": "create a pin for an user"
      }
    },
    "/pins/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "pin"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the deleted **pin**.",
        "operationId": "pins.delete",
        "summary": "deletes a pin by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "pin.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a **pin** object by key.",
        "operationId": "pins.get",
        "summary": "gets a pin by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "pin"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the updated **pin**.",
        "operationId": "pins.update",
        "summary": "updates a pin by key"
      }
    },
    "/powers": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "power.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **power** objects for an user",
        "operationId": "powers.list",
        "summary": "list powers of an user"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "power"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "creates a **power** object for an user",
        "operationId": "powers.create",
        "summary": "create power for an user"
      }
    },
    "/powers/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "power"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the deleted **power**.",
        "operationId": "powers.delete",
        "summary": "deletes a power by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "power.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a **power** object by key.",
        "operationId": "powers.get",
        "summary": "gets a power  by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "power"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the updated **power**.",
        "operationId": "powers.update",
        "summary": "updates a power by key"
      }
    },
    "/powers/{_key}/qualifiers": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "power",
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the **power** object identified by key.",
        "operationId": "powers.remove_qualifiers",
        "summary": "removes qualifiers for a power identified by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "power.read",
              "skill.qualifier.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **qualifier with value** object for the power identified by key.",
        "operationId": "powers.list_qualifiers",
        "summary": "lists qualifiers for a power identified by key"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "power",
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the **power** object identified by key.",
        "operationId": "powers.add_qualifiers",
        "summary": "adds qualifiers for a power identified by key"
      }
    },
    "/profiles": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **profiles**.",
        "operationId": "skills.profile.list",
        "summary": "list profiles"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "creates a new **skills profile**",
        "operationId": "skills.profile.create",
        "summary": "creates skills profile"
      }
    },
    "/profiles/matching": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **profiles** that match with an user.",
        "operationId": "skills.profile.matching",
        "summary": "list profiles that match with an user"
      }
    },
    "/profiles/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the deleted **skills profile**.",
        "operationId": "skills.profile.delete",
        "summary": "deletes a skills profile by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a **skills profile** by key.",
        "operationId": "skills.profile.get",
        "summary": "gets a skills profile  by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "skill.profile"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the updated **skills profile**.",
        "operationId": "skills.profile.update",
        "summary": "updates a skills profile by key"
      }
    },
    "/qualifiers": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **qualifiers**.",
        "operationId": "skills.qualifiers.list",
        "summary": "list qualifiers"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "creates a new **qualifier**",
        "operationId": "skills.qualifier.create",
        "summary": "creates qulaifier"
      }
    },
    "/qualifiers/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the deleted **qualifier**.",
        "operationId": "skills.qualifier.delete",
        "summary": "deletes a qualifier by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a **qualifier** by key.",
        "operationId": "skills.qualifier.get",
        "summary": "gets a qualifier by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the updated **qualifier**.",
        "operationId": "skills.qualifier.update",
        "summary": "updates a qualifier by key"
      }
    },
    "/qualifiers/{_key}/powers": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier.read",
              "power.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **powers** associated to the qualifier identified by key.",
        "operationId": "skills.qualifier.list_powers",
        "summary": "lists powers associated to the qualifier identified by key"
      }
    },
    "/qualifiers/{_key}/skills": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.qualifier.read",
              "skill.skill.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **skills** associated to the qualifier identified by key.",
        "operationId": "skills.qualifier.list_skills",
        "summary": "lists skills associated to the qualifier identified by key"
      }
    },
    "/resources/{user_id}/pins/jobs": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "profile.read",
              "pin.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **pinned jobs** object.",
        "operationId": "resources.job_pins.list",
        "summary": "lists jobs pinned by user identified by <user_id>"
      }
    },
    "/resources/{user_id}/pins/trainings": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "profile.read",
              "pin.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **pinned trainings** object.",
        "operationId": "resources.training_pins.list",
        "summary": "lists trainings pinned by user identified by <user_id>"
      }
    },
    "/resources/{user_id}/powers": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "power.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **powers** object.",
        "operationId": "resources.powers.list",
        "summary": "lists powers of user identified by <user_id>"
      }
    },
    "/resources/{user_id}/skill.validations": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "validation.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **validations** object.",
        "operationId": "resources.skill_validations.list",
        "summary": "lists validations of user identified by <user_id>"
      }
    },
    "/search": {
      "post": {
        "security": [
          {
            "elamp_auth": [
              "search.search"
            ]
          }
        ],
        "tags": [
          "SEARCH"
        ],
        "description": "execute search query",
        "operationId": "search.search",
        "summary": "execute search query"
      }
    },
    "/skill.validations": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.validation.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a list of **validations** objects for an user",
        "operationId": "skills.validations.list",
        "summary": "list skills validations of an user"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.validation"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "creates a **validation** object for an user",
        "operationId": "skills.validation.create",
        "summary": "create a validation for an user"
      }
    },
    "/skill.validations/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.validation"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the deleted **validation**.",
        "operationId": "skills.validations.delete",
        "summary": "deletes a validation by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.validation.read"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns a **validation** object by key.",
        "operationId": "skills.validations.get",
        "summary": "gets a validation by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "skill.validation"
            ]
          }
        ],
        "tags": [
          "RUN"
        ],
        "description": "returns the updated **validation**.",
        "operationId": "skills.validations.update",
        "summary": "updates a validation by key"
      }
    },
    "/skills": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **skills**.",
        "operationId": "skills.skills.list",
        "summary": "list skills"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "creates a new **skills**",
        "operationId": "skills.skill.create",
        "summary": "creates skills"
      }
    },
    "/skills/search": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **skill** objects.",
        "operationId": "skills.skill.search",
        "summary": "searches skill by name"
      }
    },
    "/skills/{_key}": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the deleted **skill**.",
        "operationId": "skills.skill.delete",
        "summary": "deletes a skill by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a **skill** by key.",
        "operationId": "skills.skill.get",
        "summary": "gets a skill by key"
      },
      "patch": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns the updated **skill**.",
        "operationId": "skills.skill.update",
        "summary": "updates a skill by key"
      }
    },
    "/skills/{_key}/qualifiers": {
      "delete": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill",
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **qualifier** objects for the requested skill.",
        "operationId": "skills.skill.remove_qualifiers",
        "summary": "remove qualifiers from a skill identified by key"
      },
      "get": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill.read",
              "skill.qualifier.read"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **qualifier** objects for the requested skill.",
        "operationId": "skills.skill.list_qualifiers",
        "summary": "list qualifiers of a skill identified by key"
      },
      "post": {
        "security": [
          {
            "elamp_auth": [
              "skill.skill",
              "skill.qualifier"
            ]
          }
        ],
        "tags": [
          "COMPOSE"
        ],
        "description": "returns a list of **qualifier** objects for the requested skill.",
        "operationId": "skills.skill.add_qualifiers",
        "summary": "add qualifiers to a skill identified by key"
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "user.read"
            ]
          }
        ],
        "tags": [
          "IAM"
        ],
        "description": "returns a list of **user** objects.",
        "operationId": "iam.users.list",
        "summary": "lists users"
      }
    },
    "/users/{_key}": {
      "get": {
        "security": [
          {
            "elamp_auth": [
              "user.read"
            ]
          }
        ],
        "tags": [
          "IAM"
        ],
        "description": "returns an **user** object.",
        "operationId": "iam.users.get",
        "summary": "get user by id"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "elamp_auth": {
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://elamp.fr/oauth/authorize",
            "scopes": {
              "pin": "read and manage pins",
              "pin.read": "read pins",
              "power": "read and manage your powers",
              "power.read": "read your powers (competencies)",
              "search.analyze": "execute analytics query",
              "search.search": "execute search query",
              "skill.library": "read and manage your skill libraries",
              "skill.library.read": "read your skill libraries",
              "skill.profile": "read and manage your skills profiles",
              "skill.profile.read": "read your skills profiles",
              "skill.qualifier": "read and manage your qualifiers",
              "skill.qualifier.read": "read your qualifiers",
              "skill.skill": "read and manage your skills",
              "skill.skill.read": "read your skills",
              "skill.validation": "read and manage your power validations",
              "skill.validation.read": "read your power validations"
            },
            "tokenUrl": "https://elamp.fr/oauth/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "description": "Identity and Access Management",
      "name": "IAM"
    },
    {
      "description": "libraries, skills, qualifiers and skills profiles endpoints",
      "name": "COMPOSE"
    },
    {
      "description": "powers, skill validation, pins endpoints",
      "name": "RUN"
    },
    {
      "description": "search and analytics endpoints",
      "name": "SEARCH"
    }
  ]
}