openapi: "3.0.0"
info:
  title: eLamp Web API
  x-logo:
    url: https://d13ohmdfxbevj9.cloudfront.net/assets/img/LOGO-SLOGAN-COLOR-ALPHA-SMALL.png
    altText: eLamp Web API
  description: ""
  termsOfService: "https://www.elamp.fr/"
  version: "1.0.0"
  contact:
    name: API support
    email: support@elamp.fr
  license:
    name: eLamp
    url: https://www.elamp.fr/
servers:
  - url: https://api.elamp.fr/v1
x-tagGroups:
  - name: Identity & Access Management (IAM)
    tags:
      - Users
      - Groups
      - Roles
  - name: Compose
    tags:
      - Libraries
      - Skills
      - Qualifiers
      - Jobs & Trainings
  - name: Run
      - Powers
      - Validations
      - Pins
      - Resources
  - name: Search
    tags:
      - Search
tags:
  - name: Users
    description: Users Management
  - name: Groups
    description: Groups Management
  - name: Roles
    description: Roles Management
  - name: Libraries
    description: Libraries (skills's containers) endpoints
  - name: Skills
    description: Skills definition endpoints
  - name: Qualifiers
    description: Qualifiers management
  - name: Jobs & Trainings
    description: Jobs & Trainings definition
  - name: Powers
    description: Users' skills
  - name: Search
    description: search and analytics endpoints
components:
  securitySchemes:
    elamp_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://elamp.fr/oauth/authorize
          tokenUrl: https://elamp.fr/oauth/token
          scopes:
            skill.library.read: read your skill libraries
            skill.library: read and manage your skill libraries
            skill.skill.read: read your skills
            skill.skill: read and manage your skills
            skill.qualifier.read: read your qualifiers
            skill.qualifier: read and manage your qualifiers
            skill.profile.read: read your skills profiles
            skill.profile: read and manage your skills profiles
            power.read: read your powers (competencies)
            power: read and manage your powers
            skill.validation.read: read your power validations
            skill.validation: read and manage your power validations
            pin.read: read pins
            pin: read and manage pins

            search.search: execute search query
            search.analyze: execute analytics query
paths:
  /libraries:
    get:
      operationId: skills.libraries.list
      summary: lists libraries
      description: returns a list of available **skills libraries**
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library.read
    post:
      operationId: skills.libraries.create
      summary: creates libraries
      description: creates a new **skills library**
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library

  /libraries/{_key}:
    get:
      operationId: skills.libraries.get
      summary: gets a library by key
      description: returns a **skills library** by key.
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library.read

    patch:
      operationId: skills.libraries.update
      summary: updates a library by key
      description: |
        returns the updated **library**.
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library
    delete:
      operationId: skills.libraries.delete
      summary: deletes a library by key
      description: |
        returns the deleted **library**.
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library

  /libraries/{_key}/subscribe:
    post:
      operationId: skills.libraries.subscribe
      summary: subscribe to a library by key
      description: returns the subscribed **skills library**.
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library
  /libraries/{_key}/unsubscribe:
    post:
      operationId: skills.libraries.unsubscribe
      summary: unsubscribe to a library by key
      description: returns the unsubscribed **skills library**.
      tags:
        - Libraries
      security:
        - elamp_auth:
            - skill.library

  /skills:
    get:
      operationId: skills.skills.list
      summary: list skills
      description: returns a list of **skills**.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill.read
    post:
      operationId: skills.skill.create
      summary: creates skills
      description: creates a new **skills**
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill
  /skills/search:
    get:
      operationId: skills.skill.search
      summary: searches skill by name
      description: returns a list of **skill** objects.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill.read

  /skills/{_key}:
    get:
      operationId: skills.skill.get
      summary: gets a skill by key
      description: returns a **skill** by key.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill.read

    patch:
      operationId: skills.skill.update
      summary: updates a skill by key
      description: returns the updated **skill**.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill
    delete:
      operationId: skills.skill.delete
      summary: deletes a skill by key
      description: returns the deleted **skill**.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill

  /skills/{_key}/qualifiers:
    get:
      operationId: skills.skill.list_qualifiers
      summary: list qualifiers of a skill identified by key
      description: returns a list of **qualifier** objects for the requested skill.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill.read
            - skill.qualifier.read
    post:
      operationId: skills.skill.add_qualifiers
      summary: add qualifiers to a skill identified by key
      description: returns a list of **qualifier** objects for the requested skill.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill
            - skill.qualifier
    delete:
      operationId: skills.skill.remove_qualifiers
      summary: remove qualifiers from a skill identified by key
      description: returns a list of **qualifier** objects for the requested skill.
      tags:
        - Skills
      security:
        - elamp_auth:
            - skill.skill
            - skill.qualifier

  /qualifiers:
    get:
      operationId: skills.qualifiers.list
      summary: list qualifiers
      description: returns a list of **qualifiers**.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier.read
    post:
      operationId: skills.qualifier.create
      summary: creates qulaifier
      description: creates a new **qualifier**
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.skill

  /qualifiers/{_key}:
    get:
      operationId: skills.qualifier.get
      summary: gets a qualifier by key
      description: returns a **qualifier** by key.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier.read

    patch:
      operationId: skills.qualifier.update
      summary: updates a qualifier by key
      description: returns the updated **qualifier**.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier
    delete:
      operationId: skills.qualifier.delete
      summary: deletes a qualifier by key
      description: returns the deleted **qualifier**.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier
  /qualifiers/{_key}/skills:
    get:
      operationId: skills.qualifier.list_skills
      summary: lists skills associated to the qualifier identified by key
      description: returns a list of **skills** associated to the qualifier identified by key.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier.read
            - skill.skill.read
  /qualifiers/{_key}/powers:
    get:
      operationId: skills.qualifier.list_powers
      summary: lists powers associated to the qualifier identified by key
      description: returns a list of **powers** associated to the qualifier identified by key.
      tags:
        - Qualifiers
      security:
        - elamp_auth:
            - skill.qualifier.read
            - power.read

  /profiles:
    get:
      operationId: skills.profile.list
      summary: list profiles
      description: returns a list of **profiles**.
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile.read
    post:
      operationId: skills.profile.create
      summary: creates skills profile
      description: creates a new **skills profile**
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile
  /profiles/matching:
    get:
      operationId: skills.profile.matching
      summary: list profiles that match with an user
      description: returns a list of **profiles** that match with an user.
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile.read
  /profiles/{_key}:
    get:
      operationId: skills.profile.get
      summary: gets a skills profile  by key
      description: returns a **skills profile** by key.
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile.read

    patch:
      operationId: skills.profile.update
      summary: updates a skills profile by key
      description: returns the updated **skills profile**.
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile
    delete:
      operationId: skills.profile.delete
      summary: deletes a skills profile by key
      description: returns the deleted **skills profile**.
      tags:
        - Jobs & Trainings
      security:
        - elamp_auth:
            - skill.profile

  /search:
    post:
      operationId: search.search
      summary: execute search query
      description: execute search query
      tags:
        - Search
      security:
        - elamp_auth:
            - search.search

  /powers:
    get:
      operationId: powers.list
      summary: list powers of an user
      description: returns a list of **power** objects for an user
      tags:
        - Powers
      security:
        - elamp_auth:
            - power.read
    post:
      operationId: powers.create
      summary: create power for an user
      description: creates a **power** object for an user
      tags:
        - Powers
      security:
        - elamp_auth:
            - power
  /powers/{_key}:
    get:
      operationId: powers.get
      summary: gets a power  by key
      description: returns a **power** object by key.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power.read

    patch:
      operationId: powers.update
      summary: updates a power by key
      description: returns the updated **power**.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power
    delete:
      operationId: powers.delete
      summary: deletes a power by key
      description: returns the deleted **power**.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power

  /powers/{_key}/qualifiers:
    get:
      operationId: powers.list_qualifiers
      summary: lists qualifiers for a power identified by key
      description: returns a list of **qualifier with value** object for the power identified by key.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power.read
            - skill.qualifier.read
    post:
      operationId: powers.add_qualifiers
      summary: adds qualifiers for a power identified by key
      description: returns the **power** object identified by key.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power
            - skill.qualifier
    delete:
      operationId: powers.remove_qualifiers
      summary: removes qualifiers for a power identified by key
      description: returns the **power** object identified by key.
      tags:
        - Powers
      security:
        - elamp_auth:
            - power
            - skill.qualifier

  /skill.validations:
    get:
      operationId: skills.validations.list
      summary: list skills validations of an user
      description: returns a list of **validations** objects for an user
      tags:
        - Validations
      security:
        - elamp_auth:
            - skill.validation.read
    post:
      operationId: skills.validation.create
      summary: create a validation for an user
      description: creates a **validation** object for an user
      tags:
        - Validations
      security:
        - elamp_auth:
            - skill.validation
  /skill.validations/{_key}:
    get:
      operationId: skills.validations.get
      summary: gets a validation by key
      description: returns a **validation** object by key.
      tags:
        - Validations
      security:
        - elamp_auth:
            - skill.validation.read

    patch:
      operationId: skills.validations.update
      summary: updates a validation by key
      description: returns the updated **validation**.
      tags:
        - Validations
      security:
        - elamp_auth:
            - skill.validation
    delete:
      operationId: skills.validations.delete
      summary: deletes a validation by key
      description: returns the deleted **validation**.
      tags:
        - Validations
      security:
        - elamp_auth:
            - skill.validation
  /pins:
    get:
      operationId: pins.list
      summary: list pins of an user
      description: returns a list of **pin** objects for an user
      tags:
        - Pins
      security:
        - elamp_auth:
            - pin.read
    post:
      operationId: pins.create
      summary: create a pin for an user
      description: creates a **pin** object for an user
      tags:
        - Pins
      security:
        - elamp_auth:
            - pin
  /pins/{_key}:
    get:
      operationId: pins.get
      summary: gets a pin by key
      description: returns a **pin** object by key.
      tags:
        - Pins
      security:
        - elamp_auth:
            - pin.read

    patch:
      operationId: pins.update
      summary: updates a pin by key
      description: returns the updated **pin**.
      tags:
        - Pins
      security:
        - elamp_auth:
            - pin
    delete:
      operationId: pins.delete
      summary: deletes a pin by key
      description: returns the deleted **pin**.
      tags:
        - Pins
      security:
        - elamp_auth:
            - pin
  /resources/{user_id}/powers:
    get:
      operationId: resources.powers.list
      summary: lists powers of user identified by <user_id>
      description: returns a list of **powers** object.
      tags:
        - Resources
      security:
        - elamp_auth:
            - power.read
  /resources/{user_id}/skill.validations:
    get:
      operationId: resources.skill_validations.list
      summary: lists validations of user identified by <user_id>
      description: returns a list of **validations** object.
      tags:
        - Resources
      security:
        - elamp_auth:
            - validation.read
  /resources/{user_id}/pins/jobs:
    get:
      operationId: resources.job_pins.list
      summary: lists jobs pinned by user identified by <user_id>
      description: returns a list of **pinned jobs** object.
      tags:
        - Resources
      security:
        - elamp_auth:
            - profile.read
            - pin.read
  /resources/{user_id}/pins/trainings:
    get:
      operationId: resources.training_pins.list
      summary: lists trainings pinned by user identified by <user_id>
      description: returns a list of **pinned trainings** object.
      tags:
        - Resources
      security:
        - elamp_auth:
            - profile.read
            - pin.read

  /users:
    get:
      operationId: iam.users.list
      summary: lists users
      description: returns a list of **user** objects.
      tags:
        - Users
      security:
        - elamp_auth:
            - user.read

  /users/{_key}:
    get:
      operationId: iam.users.get
      summary: get user by id
      description: returns an **user** object.
      tags:
        - Users
      security:
        - elamp_auth:
            - user.read

  /groups:
    get:
      operationId: iam.groups.list
      summary: lists groups
      description: returns a list of **group** objects.
      tags:
        - Groups
      security:
        - elamp_auth:
            - group.read

  /groups/{_key}:
    get:
      operationId: iam.groups.get
      summary: get group by id
      description: returns a single **group** object.
      tags:
        - Groups
      security:
        - elamp_auth:
            - group.read
